jenkinsci/copyartifact-plugin

src/main/java/hudson/plugins/copyartifact/LastCompletedBuildSelector.java, src/main/resources/hudson/plugins/copyartifact/Messages.properties
Allows to select the last build ignoring the build status completely.
This allows to copy artifacts also from failed jobs.
=> Add new "last build" selector

src/test/java/hudson/plugins/copyartifact/CopyArtifactWorkflowTest.java
An additional trivial change for #55.
Workflow step `sh` doesn't work on Windows.
Let's use `writeFile` instead: https://github.com/jenkinsci/workflow-plugin/blob/master/basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/WriteFileStep.java.
=> [JENKINS-24487] Allows tests run on Windows

src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
https://issues.jenkins-ci.org/browse/JENKINS-14999
#24 
Tests for QueueItemAuthenticator was disabled as QueueItemAuthenticator was introduced since Jenkins 1.521, and copyartifact targets for Jenkins 1.509.
Now copyartifact targets for Jenkins 1.580.1 and they should work now.
=> [JENKINS-14999] Enabled tests for QueueItemAuthenticator

src/main/java/hudson/plugins/copyartifact/ParametersBuildFilter.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactWorkflowTest.java
https://issues.jenkins-ci.org/browse/JENKINS-26694
`ParametersBuildFilter` doesn't work for `WorkflowJob`s as it extract parameters of upstream builds with `Run#getEnvironemnt(TaskListener)`.
You can extract build parameters from environments only in `AbstractBuild`s, and `WorkflowJob` is a subclass of `Run`, not `AbstractBuild`.
This is a workaround for that problem.
=> [JENKINS-26694] Make ParameterBuildFilter applicable to WorkflowJobs.

src/main/java/hudson/plugins/copyartifact/CopyArtifact.java
A fix for [JENKINS-27475](https://issues.jenkins-ci.org/browse/JENKINS-27475).
This NPE happens when:
* `Copyartifact#project` is `null`
* `Copyartifact#projectName` is `null`
As far as I know, this should not be happen. I don't know how to reproduce that NPE.
Though, the fix is easy and harmless, and I plan to include this fix in the next release.
=> [JENKINS-27475] Avoids NPE on renaming a project.

pom.xml, src/main/java/hudson/plugins/copyartifact/BuildSelector.java, src/main/java/hudson/plugins/copyartifact/BuildSelectorParameter.java, src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/main/java/hudson/plugins/copyartifact/CopyArtifactPermissionProperty.java, src/main/java/hudson/plugins/copyartifact/DownstreamBuildSelector.java, src/main/java/hudson/plugins/copyartifact/FilePathCopyMethod.java, src/main/java/hudson/plugins/copyartifact/FingerprintingCopyMethod.java, src/main/java/hudson/plugins/copyartifact/ParametersBuildFilter.java, src/main/java/hudson/plugins/copyartifact/PermalinkBuildSelector.java, src/main/java/hudson/plugins/copyartifact/StatusBuildSelector.java, src/main/java/hudson/plugins/copyartifact/TriggeredBuildSelector.java
[JENKINS-29488](https://issues.jenkins-ci.org/browse/JENKINS-29488) (findbugs.xml before this fix is attached)
#67 introduced findbugs and revealed that copyartifact have many findbugs issues.
Most of them are `@CheckForNull` for `Jenkins#getInstance` (introduced in fa496c7bf228ecb243acf0135106f18f27132c6f) like:
```
<BugInstance type='NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE'
priority='Normal'
category='STYLE'
message='Possible null pointer dereference in hudson.plugins.copyartifact.BuildSelectorParameter$DescriptorImpl.getAvailableBuildSelectorList() due to return value of called method'
lineNumber='105'/>
```
I decided not to use `@SuppressFBWarnings` for this issue as it can annotate only whole methods (annotating local variables takes no effects...) and that can easily cause …
=> [JENKINS-29488] Fixed findbugs issues.

src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/config.jelly, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-resultVariableSuffix.html, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-resultVariableSuffix_ja.html, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-selector.html, src/main/resources/hudson/plugins/copyartifact/Messages.properties, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java, src/test/java/hudson/plugins/copyartifact/testutils/CopyArtifactUtil.java
[JENKINS-18938](https://issues.jenkins-ci.org/browse/JENKINS-18938)
Copyartifact stores the number of the build where copied artifacts to a variable "COPYARTIFACT_BUILD_NUMBER_(PROJECTNAME)".
Not all project names are usable for variable names and copyartifact substitutes invalid letters in project names.
That contains following problems;
* It's difficult for users to know the actual variable name where the build number is stored.
* Especially when the source project is in different folder.
* "Invalid letters" contain numeric letters even though they are actually usable for variable names.
This change introduces a new field "Result variable suffix" which specified the suffix for "COPYARTIFACT_BUILD_NUMBER_(SUFFIX)".
* It is located in "Advanced" section.
* You can specify the suffix for …
=> [JENKINS-18938] Added a field to specify the suffix for the variable to store the build number

src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/main/java/hudson/plugins/copyartifact/ParameterizedBuildSelector.java, src/main/resources/hudson/plugins/copyartifact/ParameterizedBuildSelector/help-parameterName.html, src/test/java/hudson/plugins/copyartifact/ParameterizedBuildSelectorTest.java
[JENKINS-30357](https://issues.jenkins-ci.org/browse/JENKINS-30357)
Fixed:
* ParameterizedBuildSelector doesn't work with workflow jobs as parameter variables in workflow jobs are not passed to copyartifact.
* NPE when specifying an undefined variable in ParameterizedBuildSelector.
Improved:
* Error handlings in ParameterizedBuildSelector
New features:
* You can specify immediate values (like `<SomeSelector />`) in ParameterizedBuildSelector. This is useful especially with workflow jobs, you can pass values with `${SELECTOR}` in workflow definitions.
* You can specify variable expression (like `${SELECTOR}`) in ParameterizedBuildSelector. This is to allow users to configure ParameterizedBuildSelector in freestyle projects just like workflow jobs. (to keep the compatibility of usage with …
=> [JENKINS-30357] Fixed NPE and other improvements in ParameterizedBuildSelector

src/main/java/hudson/plugins/copyartifact/TriggeredBuildSelector.java, src/main/resources/hudson/plugins/copyartifact/TriggeredBuildSelector/config.jelly, src/test/java/hudson/plugins/copyartifact/DownstreamBuildSelectorTest.java, src/test/java/hudson/plugins/copyartifact/TriggeredBuildSelectorTest.java
The CopyArtifact plugin with 'Upstream build that triggered this job' works fine for us for a chain of jobs when the build started with the first job that triggers the next one, which triggers the next, and so on. The advantage of the Upstream-build strategy is that it works even with overlapping chains of builds. But there is a problem when we have overlapping chains and the build is started with an intermediate job.
Let's consider a simple scenario: each job triggers the next one
ModuleA --> ModuleB --> Publisher
where 
ModuleB depends on artifacts of ModuleA (using the Upstream-build strategy),
Publisher copies artifacts from ModuleA and ModuleB (using the Upstream-build strategy),
ModuleB needs significantly more time to build than ModuleA, so ModuleA can build while a ModuleB build …
=> Add option to 'Upstream build that triggered this job' to allow upstream dependencies

pom.xml
Added a comment for #76 ,dependency exclusions in pom.xml.
=> Do not allow httpclient/httpcore from maven-plugin to override jenkins-test-harness deps

pom.xml, src/main/java/hudson/plugins/copyartifact/BuildSelector.java, src/main/java/hudson/plugins/copyartifact/BuildSelectorParameter.java, src/main/java/hudson/plugins/copyartifact/Copier.java, src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/main/java/hudson/plugins/copyartifact/CopyArtifactPermissionProperty.java, src/main/java/hudson/plugins/copyartifact/DownstreamBuildSelector.java, src/main/java/hudson/plugins/copyartifact/FilePathCopyMethod.java, src/main/java/hudson/plugins/copyartifact/SimpleBuildSelectorDescriptor.java, src/main/resources/index.jelly, src/test/java/hudson/plugins/copyartifact/BuildSelectorParameterTest.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactPermissionPropertyTest.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactWorkflowTest.java, src/test/java/hudson/plugins/copyartifact/SpecificBuildSelectorTest.java, src/test/java/hudson/plugins/copyartifact/TriggeredBuildSelectorTest.java
[JENKINS-33389](https://issues.jenkins-ci.org/browse/JENKINS-33389)
@reviewbybees
=> [JENKINS-33389] Adapt to new parent POM and split JTH

README.md
[JENKINS-33389](https://issues.jenkins-ci.org/browse/JENKINS-33389)
Introducing JTH >= 2.0 consuming more PermGen spaces, and requires extend it with `-XX:MaxPermSize=128m`.
=> [JENKINS-33389] Added notes about PermGen issue with Java7.

src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java, src/test/java/hudson/plugins/copyartifact/ParameterizedBuildSelectorTest.java, src/test/java/hudson/plugins/copyartifact/TriggeredBuildSelectorTest.java
[JENKINS-36314](https://issues.jenkins-ci.org/browse/JENKINS-36314?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20copyartifact-plugin%20AND%20text%20~%20%22SECURITY-170%22)
After SECURITY-170 parameterized jobs does not accept unknown build params as default, this PR explicitly sets the build params and copy permissions for the jobs used in the tests.
@reviewbybees
=> [JENKINS-36314] Tests failing after SECURITY-170

src/main/java/hudson/plugins/copyartifact/FingerprintingCopyMethod.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
[JENKINS-32832](https://issues.jenkins-ci.org/browse/JENKINS-32832)
When a symlink is in a sub directory, it may fail to be created as its parent directory is not created yet.
=> [JENKINS-32832] symlink fails to be created as the directory is not created.

pom.xml, src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/main/java/hudson/plugins/copyartifact/DownstreamBuildSelector.java, src/main/java/hudson/plugins/copyartifact/LastCompletedBuildSelector.java, src/main/java/hudson/plugins/copyartifact/ParameterizedBuildSelector.java, src/main/java/hudson/plugins/copyartifact/PermalinkBuildSelector.java, src/main/java/hudson/plugins/copyartifact/SavedBuildSelector.java, src/main/java/hudson/plugins/copyartifact/SpecificBuildSelector.java, src/main/java/hudson/plugins/copyartifact/StatusBuildSelector.java, src/main/java/hudson/plugins/copyartifact/TriggeredBuildSelector.java, src/main/java/hudson/plugins/copyartifact/WorkspaceSelector.java
See [the ticket](https://issues.jenkins-ci.org/browse/JENKINS-46700) for more details.
In order to allow symbol names on `BuildSelector` I had to turn them into fully-fledged class, since `@Symbol` cannot be placed on a field given the way it works.
=> [JENKINS-46700] symbol support for better pipeline compatibility

src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
Amends test from #42. I found that the tests which supposedly are exercising explicit excludes (JENKINS-18662) in fact pass if Ant’s default excludes are applied (contrary to JENKINS-14900) but explicit excludes are totally ignored. This is because the choice of explicit excludes happened to be files which default excludes also cover. This was confusing and not helpful for verifying the actual behavior.
Also the tests did not check the use of _multiple_ excludes.
@reviewbybees
=> [JENKINS-18662] Strengthen test to differentiate between explicit and default excludes

src/test/java/hudson/plugins/copyartifact/CopyArtifactWorkflowTest.java
https://issues.jenkins-ci.org/browse/JENKINS-47074
Jenkins 1.597+ uses the build number as the build ID, and `SpecificBuildSelector` should accept build IDs without any changes as @jglick pointed in https://github.com/jenkinsci/copyartifact-plugin/pull/101#issuecomment-373139068.
=> [JENKINS-47074] Verify SpecificBuildSelector accepts build IDs

pom.xml
Though maven-plugin-2.7.1 is sufficient for the feature of copyaritfact, it requires declaring dependency exclusions and make pom.xml complicated.
I decided to simplify pom.xml as the next version jumps the target Jenkins version and this is a good time for that.
=> Update maven-plugin to the latest

pom.xml, src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
Picks up https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin/pull/9 so that network problems need not be fatal. Follows up #100.
=> Using RobustHTTPClient utility for artifact downloads

pom.xml, src/main/java/hudson/plugins/copyartifact/CopyArtifactPermissionProperty.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactPermissionPropertyTest.java
Trying to fix up #105.
It took me a long time to get the new test to pass, and it turns out that this is because the conditions under which this feature are actually useful for Pipeline are so rarefied that it might as well not exist. It does not work if you are using a `QueueItemAuthenticator` like `authorize-project`—because if the build authentication lacks `READ` permission to upstream, [this line](https://github.com/jenkinsci/copyartifact-plugin/blob/3680ce8e6e2db2d19e66170d1cc44aa0c25d0b13/src/main/java/hudson/plugins/copyartifact/CopyArtifact.java#L411) returns null even though the project name is correct. It does not work if you simply specify the upstream project name as a string literal, since then [this line](https://github.com/jenkinsci/copyartifact-plugin/blob/3680ce8e6e2db2d1 …
=> copyArtifactPermission II

pom.xml, src/main/java/hudson/plugins/copyartifact/CopyArtifactPermissionProperty.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactPermissionPropertyTest.java
Allows this in the options block
```
pipeline {
agent any
options {
copyArtifactPermission('job1,...')
}
stages{...}
}
```
as discussed [here](https://groups.google.com/forum/#!topic/jenkinsci-dev/nJ54NaM7ctU)
=> Add pipeline property copyArtifactPermission

.mvn/extensions.xml, Jenkinsfile, pom.xml, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java, src/test/java/hudson/plugins/copyartifact/TriggeredBuildSelectorTest.java
Replaces #110.
I plan a micro release for Java11 and want minimum changes as possible, least dependency changes in the plugin.
And it’s more clear what is mandatory to make applicable to Java11.
=> Minimal changes to pass tests on Java11

src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-projectName.html
- Split into a section for each type of project, for improved clarity
- Add syntax for Multibranch Pipeline projects (as mentioned on https://issues.jenkins-ci.org/browse/JENKINS-40429#comment-343463)
=> Restructure and expand Project Name documentation

src/test/java/hudson/plugins/copyartifact/BuildSelectorParameterTest.java
Executing PCT for _copyartifact-plugin_ against newest versions of jenkins core fail because one test is instantiating CLI using a deprecated constructor that has been removed.
After the execution, `BuildSelectorParameterTest.testParameter` fails with the following trace:
```
java.lang.NoSuchMethodError: hudson.cli.CLI.<init>(Ljava/net/URL;)V
at hudson.plugins.copyartifact.BuildSelectorParameterTest.testParameter(BuildSelectorParameterTest.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at …
```
=> Remove use of deprecated CLI constructor

src/main/java/hudson/plugins/copyartifact/BuildSelectorParameter.java, src/test/java/hudson/plugins/copyartifact/BuildSelectorParameterWorkflowTest.java
`properties([parameters([buildSelector(name: 'name', description: 'description', defaultSelector: lastCompleted())])])`
instead of
`properties([parameters([$class: 'BuildSelectorParameter', name:'name', description: 'description', defaultSelector:lastCompleted()]])])`
=> Add a symbol for BuildSelectorParameter

pom.xml, src/test/java/hudson/plugins/copyartifact/CopyArtifactPermissionPropertyTest.java, src/test/java/hudson/plugins/copyartifact/monitor/LegacyMonitorDataTest.java
The failures were:
<details>
<summary>CopyArtifactPermissionPropertyTest: testNotWorkWithQueueItemAuthenticator
</summary>
```
[ERROR] testNotWorkWithQueueItemAuthenticator(hudson.plugins.copyartifact.CopyArtifactPermissionPropertyTest)  Time elapsed: 180.051 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 180 seconds
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:502)
at hudson.remoting.AsyncFutureImpl.get(AsyncFutureImpl.java:75)
at org.jvnet.hudson.test.JenkinsRule.assertBuildStatus(JenkinsRule.java:1253)
at hudson.plugins.copyartifact.CopyArtifactPermissionPropertyTest.testNotWorkWithQueueItemAuthenticator(CopyArtifactPermissionPropertyTest.java:348)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
```
=> Correct PCT failures after recent security release

Jenkinsfile, pom.xml, src/test/java/hudson/plugins/copyartifact/ParameterizedBuildSelectorTest.java
https://issues.jenkins-ci.org/browse/JENKINS-62409
* Use plugin pom 4.0: https://github.com/jenkinsci/plugin-pom/tree/plugin-4.2
* Use jenkins bom: https://github.com/jenkinsci/bom/tree/bom-10
* Specify CI configurations explicitly instead of `recommendedConfigurations`
* https://github.com/jenkins-infra/pipeline-library/pull/145
* I actually don't think that's a good idea to specify configurations explicitly as we have to update Jenkinsfile manually. But Jenkins-2.164.1, the current target with `recommendedConfigurations` is old and I believe the root cause of #119 is the issue of `recommendedConfigurations`. 
I already removed the dependency to matrix-auth in #122 .
=> [JENKINS-62409] Use plugin pom 4.0

CHANGELOG.adoc
A new release is required to have PCT passed.
=> Update changelog for 1.45

src/main/java/hudson/plugins/copyartifact/CopyArtifactConfiguration.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactConfigurationTest.java
https://issues.jenkins-ci.org/browse/JENKINS-62267
* The initializer of CopyArtifactConfiguration calls `save()` which fires `SaveableLister`s. It cause circular dependencies when startup if a `SaveableListener` calls `ExtensionFinder`.
=> [JENKINS-62267] Fix cirtular dependency while startup

README.adoc
https://issues.jenkins-ci.org/browse/JENKINS-62962
* It's inconsistent with the behavior on GUI. But it cannot be fixed for backward compatibilities.
=> [JENKINS-62962] Fix documentation for fingerprintArtifacts of pipeline

src/main/resources/hudson/plugins/copyartifact/BuildSelectorParameter/index.jelly
https://issues.jenkins-ci.org/browse/JENKINS-63185
* Configure the description of BuildSelectorParameter
* The description is not shown on Build with parameter page:
* This change fixes the issue and displays the description:
* Limitation: the description is displayed below the help area though Jenkins standard layouts displays description above the help area. It's for f:dropdownDescriptorSelector doesn't support description.
=> [FIXED JENKINS-63185] Display the description of BuildSelectorParameter

src/main/java/hudson/plugins/copyartifact/BuildSelectorParameter.java, src/main/java/hudson/plugins/copyartifact/CopyArtifactPermissionProperty.java, src/main/java/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitor.java, src/main/java/hudson/plugins/copyartifact/monitor/LegacyMonitorData.java, src/test/java/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitorTest.java
To avoid any potential binary incompatibilities between Guava 11 and the latest version of Guava in the forthcoming upgrade of Guava from Jenkins core, remove the Guava dependency from this plugin. This plugin doesn't need Guava; all its needs can be satisfied with native Java Platform functionality.
=> [JENKINS-65988] Remove usages of Guava

src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java, src/test/java/hudson/plugins/copyartifact/TriggeredBuildSelectorTest.java, src/test/java/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitorMigrationTest.java
Whilst investigating a different issue the tests that used maven would
reliably fail as my maven `settings.xml` is not compatible with Maven2 (as
it uses some maven 3 features).
Maven2 was end of line in 2014-02-18 so just bump the plugin to use maven3 (still an old version of 3, but better than 2!) in its tests.
=> Use Maven3 for tests

src/main/java/hudson/plugins/copyartifact/CopyArtifactConfiguration.java
This method is changing in jenkinsci/jenkins#6025 to throw `IOException`, so callers need to be adapted.
=> Compatibility with jenkins-2.325 and later (jenkinsci/jenkins#6025)

src/main/resources/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitor/manage.jelly, src/main/resources/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitor/resources.css
The change proposed prepares the plugin for the icon path removal from core in the upcoming LTS line. This change affects plugins not using the icon API or relying on paths. Plugins using the API properly in the first place are unaffected by this change.
Could you trigger a release after merging this PR please, giving people a chance to update the plugin before updating to the next LTS version @ikedam 
Thanks in advance!
=> Adapt icon path removal from core

src/test/java/hudson/plugins/copyartifact/testutils/CopyArtifactJenkinsRule.java
The HttpClient 3.x library has been removed from Jenkins 2.379.  This test depended on that library to provide a definition of HTTP status code 405, "Not allowed".  Replace the reference to that Java class with a constant.
See https://github.com/jenkinsci/bom/pull/1602 for BOM pull request that detected the issue.
I believe we'll need a new release of the copyartifact plugin and then an update to the plugin bill of materials to include that new release of the copyartifact plugin.
Prior to this pull request, the failure is visible with:
```
$ mvn clean -Dtest=InjectedTest -Djenkins.version=2.379 test
```
@basil would you be willing to review this pull request?
=> Replace HttpStatus import with a constant

pom.xml, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
Problematic for various reasons (not in BOM, uses an obsolete library, pulls in BouncyCastle not through the plugin). Easiest to just remove this test dep as it should add no interesting test coverage beyond what we already get from the `workflow-api:tests` dep. See https://github.com/jenkinsci/bom/pull/1689#issuecomment-1386975882 for context.
=> Removing test dep on `compress-artifacts`

Jenkinsfile, pom.xml, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
- Removing test dep on `compress-artifacts`
- Remove cobertura reporting, jacoco provided by parent
- Require Jenkins 2.361.4 or newer
- Do not test Java 8 in CI
Includes #163 and supersedes #159 and #162
=> Require Jenkins 2.361.4 or newer (Java 11)

pom.xml
The plugin compatbility tester reports that the upgrade of the maven
integration plugin dependency from 3.16 to 3.19 is a problem.
https://github.com/jenkinsci/bom/pull/1703/checks is the archive of the
failing checks.
There was no strong reason to upgrade to the newer integration plugin
version in the previous release.  I upgraded because 3.19 is reasonably
recent (released 8 months ago) and after the upgrade to Jenkins 2.321+
that was done in 3.17.
Restoring the minimum dependency to 3.16 does not prevent users from
installing or using more recent releases of the maven integration plugin.
=> Use optional maven integration 3.16, not 3.19

src/main/resources/hudson/plugins/copyartifact/CopyArtifact/config_de.properties, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/config_ja.properties
https://github.com/jenkinsci/copyartifact-plugin/pull/169 added empty translation strings.  They will cause the two items to be shown as empty strings in the local language versions (German and Japanese).  Better to remove the empty translation properties so that the English will be displayed.
=> Remove empty translation properties

pom.xml
Reverts jenkinsci/copyartifact-plugin#174
See discussion in https://github.com/jenkinsci/bom/pull/1978 for the detailed motivation for this change.
It is generally good to upgrade dependencies, but in this case, the upgraded dependency complicates the Jenkins plugin bill of materials.  Rather than complicate something that is widely used in the Jenkins project, let's intentionally retain this optional dependency at its older version.
This pull request is ready for review because the incremental build of the pull request evaluated successfully in the Jenkins plugin bill of materials.  @allancth, once this is merged, it will generate a new release.
=> Revert "Bump maven-plugin from 3.16 to 3.21"

src/main/resources/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitor/resources.js
See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. To test this, I instrumented the code with
```java
diff --git a/src/test/java/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitorMigrationTest.java …
```
=> Replace Prototype.js with native JavaScript

.github/dependabot.yml, pom.xml
- Revert "Bump maven-plugin from 3.16 to 3.22 (#184)"
- Exclude maven plugin from dependabot updates
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
reviewed in hopes of getting the correct syntax to disable updates of
the maven plugin.
=> Revert maven plugin upgrade

Jenkinsfile, pom.xml
Several of the tests are long running and benefit significantly from parallel execution.  Use parallel execution to speed the tests.
- Remove unused dependency references
- Run parallel tests in CI
Tests run successfully on Java 11 on my Linux computer.  Rely on ci.jenkins.io to test other configurations.
=> Run parallel tests in CI

pom.xml
the hard coded surefire config means it can not be overridden in CI or the CLI.
Whilst forkCount is the most pressing - if unlimited threads really are used, that would seem like an issue for people on slow computers, or VMs with not a lot of CPU.
amends: #198 
checked https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fcopyartifact-plugin/detail/PR-199/1/pipeline/70#step-88-log-892 is still running multiple tests in parallel
```[tasklist]
```
=> Remove hard coded surefire config

src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/test/java/hudson/plugins/copyartifact/LastStableBuildSelectorTest.java
When doing  e.g.
```
def selector = someCondition ? specific(BUILD)) : null;
copyArtifacts(fingerprintArtifacts: true, selector: selector, projectName: "someProject")
```
leads to: 
```
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: xyz
java.lang.NullPointerException
at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:482)
at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Execu …
```
=> Fixed NPE when setting selector explicitly to null from groovy

.github/dependabot.yml, pom.xml, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactWorkflowTest.java, src/test/java/hudson/plugins/copyartifact/DownstreamBuildSelectorTest.java, src/test/java/hudson/plugins/copyartifact/LastCompletedBuildSelectorTest.java
Continuing #203 & #205, trying to stabilize the test suite here which is apparently loaded with cases of background activity of unclear timing.
=> Update dependencies and stabilize tests

README.adoc
This pull request adds a minor update to the readme.
The reason I am adding this, is that recently we ran into a issue where we were suddenly seeing the 
```
Unable to find project for artifact copy: YOUR_PROJECT_WITH_ARTIFACTS
This may be due to incorrect project name or permission settings; see help for project name in job configuration.
Build step 'Copy artifacts from another project' marked build as failure
```
message after a Jenkins Update and couldn't figure out why.  It was only after looking at the source code (in particular [here](https://github.com/jenkinsci/copyartifact-plugin/blob/master/src/main/java/hudson/plugins/copyartifact/CopyArtifact.java#L594-L601)) that I was able to determine the issue.
This PR is a suggestion to include this additional line in the readme, as I …
=> Update readme to highlight interaction between "Authenticated" user group and Permission checking

pom.xml
Hi,
Latest release is pulling deprecated dependencies (see bellow)
```
copyartifact depends on:
matrix-project 802.v8013b_40c7edc
```
```
matrix-project depends on:
junit 1189.v1b_e593637fa_e
...
```
```
junit depends on:
bootstrap5-api 5.2.1-3
...
```
```
bootstrap5-api depends on:
font-awesome-api 6.2.0-3
popper2-api 2.11.6-1 <-- This is deprecated and don't want this
```
A release will be appreciated
Only automated tests
```[tasklist]
```
=> Require minimum Jenkins 2.414.3

src/test/java/hudson/plugins/copyartifact/testutils/CopyArtifactJenkinsRule.java
Thanks to @basil for raising awareness of this - https://github.com/jenkinsci/jenkins/pull/9148#issuecomment-2168720511. 
We're now using the JavaScript `fetch()` API for the builds widget which requires a polyfill for HtmlUnit. This polyfill is enabled by default as part of the Jenkins test harness `createWebClient()`, however in this case that method wasn't used as a couple of methods of WebClient needed to be overridden. 
This MR enables the polyfill for that web client.
* Test passes on latest snapshot
=> Fix WebClient missing polyfill

pom.xml, src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/test/java/hudson/plugins/copyartifact/OptionalDepsTest.java
Aligned with https://github.com/jenkinsci/htmlpublisher-plugin/pull/287.
=> Make dep on `matrix-project` optional

pom.xml, src/main/resources/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitor/resources.js
Now that Prototype.js has been removed in 2.426.x, we can remove the no-longer needed `Object.toJSON` workaround.
`mvn clean verify -DskipTests`
=> Simplify JSON parsing

src/main/java/hudson/plugins/copyartifact/FingerprintingCopyMethod.java
Stop handling not used and deprecated `PosixException` which was thrown before Jenkins 2.339. But the pom has today a minimum Jenkins version of [2.426.3](https://github.com/jenkinsci/copyartifact-plugin/blob/master/pom.xml#L31).
With a few other PRs we might be able to remove the `PosixException` from core.
Ran tests locally
=> Stop handling `PosixException` that is no longer thrown

src/main/resources/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitor/manage.jelly, src/main/resources/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitor/resources.js
https://issues.jenkins.io/browse/JENKINS-73956
To activate the monitor I've installed the version of the plugin that does not have the fix for SECURITY-988, i.e. 1.43.1.
I've set up `src` job that does `echo 123 > file.txt` and archives the artifacts. Other jobs have Copy artifacts from another project step with `src` being the project name to copy artifacts from.
In security configuration I've enabled project based matrix auth strategy (from matrix-auth). I've added a user that has `Item.READ` and `Item.BUILD` permissions. For the `src` project that archives the artifact I've taken that permission away by enabling project-based security and setting "Do not inherit...". I've built all the jobs at least once, starting from the `src`. 
After that I've upgraded the plugin to the latest …
=> [JENKINS-73956] Extract inline event handlers from `LegacyJobConfigMigrationMonitor/manage.jelly`

pom.xml, src/test/java/hudson/plugins/copyartifact/testutils/CopyArtifactJenkinsRule.java
Require Jenkins 2.452.4
Over 80% of [installations of the last two releases](https://stats.jenkins.io/pluginversions/copyartifact.html) are already on Jenkins 2.452.4 or newer.
Automated tests only
=> Require Jenkins 2.452.4

src/main/resources/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitor/manage.jelly
=> drop yui button

src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
Windows 10 and Windows 11 do not allow symbolic links to be created unless the permission is granted to the user in group policy and the Windows developer mode is enabled.
https://gist.github.com/huenisys/1efb64e57c37cfab7054c65702588fce provides one description.
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/security-policy-settings/create-symbolic-links warns that it is a security risk to allow symbolic links in applications that are not designed to handle them.
Confirmed that tests are skipped as expected when on a Windows computer without symlink support.
=> Skip CopyArtifactTest#testSymlinks tests on Windows if no symlink support

src/test/java/hudson/plugins/copyartifact/TriggeredBuildSelectorTest.java
Test was already allowing up to 3.5 seconds before checking.  Let's try double that amount of time to see if it helps.
Test is currently failing on the master branch and on two pull requests:
* https://github.com/jenkinsci/copyartifact-plugin/pull/273
* https://github.com/jenkinsci/copyartifact-plugin/pull/274
None.  Rely on ci.jenkins.io to check it.
=> Wait even longer on Windows test
