jenkinsci/copyartifact-plugin

src/test/java/hudson/plugins/copyartifact/LastCompletedBuildSelectorTest.java
[JENKINS-16476] (https://issues.jenkins-ci.org/browse/JENKINS-16476)
Tests for #53.
=> [JENKINS-16476] Tests for Last Completed Build

src/main/java/hudson/plugins/copyartifact/FingerprintingCopyMethod.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
[JENKINS-20546](https://issues.jenkins-ci.org/browse/JENKINS-20546)
=> [JENKINS-20546] Preserve symlinks when copying artifacts

pom.xml
https://issues.jenkins-ci.org/browse/JENKINS-26891
https://github.com/jenkinsci/jenkins/blob/jenkins-1.580.1/war/pom.xml#L364
=> [JENKINS-26891] Depends on matrix-project plugin bundled in Jenkins core

src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
[JENKINS-36554](https://issues.jenkins-ci.org/browse/JENKINS-36554)
=> [JENKINS-36554] Empty variables are removed and not expanded.

Jenkinsfile
buildPlugin() provided by: https://github.com/jenkins-infra/pipeline-library
=> Provide a Jenkinsfile build/testing on ci.jenkins.io

pom.xml, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
=> POM update

src/main/java/hudson/plugins/copyartifact/TriggeredBuildSelector.java
[JENKINS-47905](https://issues.jenkins-ci.org/browse/JENKINS-47905)
=> [JENKINS-47905] Provide a default constructor for TriggeredBuildSelector

.gitignore, .mvn/extensions.xml, .mvn/maven.config, pom.xml, src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/main/java/hudson/plugins/copyartifact/ParametersBuildFilter.java, src/main/resources/hudson/plugins/copyartifact/Messages.properties, src/test/java/hudson/plugins/copyartifact/BuildSelectorParameterTest.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
Subsumes #99 but extended to take advantage of https://github.com/jenkinsci/jenkins/pull/3302. Also downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/67.
@reviewbybees
=> [JENKINS-22637] ArtifactManager support on new core

CHANGELOG.adoc
* It was left as TBD
* Also added a link to the security advisory.
=> [SECURITY-988] Fix the release date of copyartifact-1.44

src/test/java/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitorMigrationTest.java
Those kind of issues are once fixed in https://github.com/jenkinsci/copyartifact-plugin/pull/113,
but degraded in copyartifact-1.44
=> [JENKINS-62586] Fix test failures in Java11

CHANGELOG.adoc
=> Fix the version number in changelog

.mvn/extensions.xml, pom.xml
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.
=> Bump parent

CHANGELOG.adoc
https://issues.jenkins-ci.org/browse/JENKINS-63185
https://github.com/jenkinsci/copyartifact-plugin/pull/131
=> Update CHANGELOG for 1.45.2

src/main/resources/hudson/plugins/copyartifact/BuildSelectorParameter/index.jelly
https://issues.jenkins.io/browse/JENKINS-64189
=> JENKINS-64189 Fix plugin on Jenkins > 2.263

pom.xml, src/main/java/hudson/plugins/copyartifact/BuildSelectorParameter.java, src/test/java/hudson/plugins/copyartifact/BuildSelectorParameterWorkflowTest.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactWorkflowTest.java
https://issues.jenkins.io/browse/JENKINS-61811
=> [JENKINS-61811] Fix NotSerializableException using declarative parameter buildSelector

CHANGELOG.adoc, README.adoc, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-projectName.html, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-projectName_de.html, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-projectName_ja.html, src/main/resources/hudson/plugins/copyartifact/Messages.properties, src/main/resources/hudson/plugins/copyartifact/Messages_de.properties, src/main/webapp/help-workspace.html, src/main/webapp/help-workspace_de.html, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
Remove usage of master, slave, blacklist, whitelist
=> [JENKINS-65398] Terminology updates

src/main/java/hudson/plugins/copyartifact/BuildSelector.java, src/main/java/hudson/plugins/copyartifact/CopyArtifact.java, src/main/java/hudson/plugins/copyartifact/CopyArtifactConfiguration.java, src/main/java/hudson/plugins/copyartifact/CopyArtifactPermissionProperty.java, src/main/java/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitor.java, src/main/java/hudson/plugins/copyartifact/monitor/LegacyMonitorData.java, src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java, src/test/java/hudson/plugins/copyartifact/monitor/LegacyJobConfigMigrationMonitorTest.java, src/test/java/hudson/plugins/copyartifact/monitor/LegacyMonitorDataTest.java
Adapting to jenkinsci/jenkins#4604.
=> Use findbugs annotations instead of jsr-305 annotations

src/main/java/hudson/plugins/copyartifact/FingerprintingCopyMethod.java
Compatible with jenkinsci/jenkins#6345.
=> Catch both `PosixException` and `IOException`

CHANGELOG.adoc
Preparation for releasing copyartifact-1.46.3.
=> Prepare changelog for 1.46.3

CHANGELOG.adoc
1.46.4 Includes
* https://github.com/jenkinsci/copyartifact-plugin/pull/147
=> Update changelog for 1.46.4

CHANGELOG.adoc
Preparing release of copyartifact-1.47.
That includes:
* #150
=> Update CHANGELOG.adoc for copyartifact-1.47

pom.xml, src/spotbugs/excludesFilter.xml
Declare specific exclusions for known cases.
=> Increase spotbugs checks

src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-fingerprintArtifacts.html, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-flatten.html, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-optional.html, src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-projectName.html
- Add Pipeline help for three flags
- Replace wiki reference with current docs
The existing Pipeline help is missing descriptions for three parameters.
=> Add more help

pom.xml
=> Remove unnecessary version override

src/test/java/hudson/plugins/copyartifact/TriggeredBuildSelectorTest.java
The Windows failures are only reporting the difference in numbers.  Maybe the job name will help diagnose the test failures.
Confirmed that assertion failure message includes the job name for more diagnosis.
=> Fix flaky test on Windows

pom.xml, src/test/java/hudson/plugins/copyartifact/OptionalDepsTest.java, src/test/java/hudson/plugins/copyartifact/SimpleBuildSelectorDescriptorTest.java
This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
=> Migrate tests to JUnit5
